insert into product (name, description, price, category_id)
values ('Liners - Baking Cups', 'fusce consequat', 326.43, 3),
       ('Irish Cream - Baileys', 'ligula pellentesque ultrices', 635.69, 2),
       ('Chickensplit Half', 'pellentesque', 415.37, 4),
       ('Mince Meat - Filling', 'vestibulum eget', 872.16, 1),
       ('Table Cloth 120 Round White', 'fusce consequat', 492.4, 3),
       ('Celery', 'sodales sed', 249.47, 4),
       ('Pastry - Apple Large', 'ultrices', 313.38, 2),
       ('Kellogs Special K Cereal', 'nonummy', 753.38, 2),
       ('Flour - Teff', 'mi', 739.64, 4),
       ('Juice Peach Nectar', 'nisl venenatis', 474.97, 2),
       ('Rabbit - Frozen', 'ultrices libero', 481.96, 2),
       ('Herb Du Provence - Primerba', 'dapibus augue vel', 935.05, 3),
       ('Sugar - Cubes', 'rutrum', 239.21, 2),
       ('Nut - Walnut, Chopped', 'praesent lectus vestibulum', 446.0, 1),
       ('Onions - Cippolini', 'nulla ultrices aliquet', 529.37, 2),
       ('Drambuie', 'consequat', 694.61, 2),
       ('Danishes - Mini Cheese', 'fermentum justo nec', 295.16, 3),
       ('Amarula Cream', 'turpis donec posuere', 302.0, 2),
       ('Pasta - Fusili, Dry', 'curae', 214.0, 1),
       ('Mackerel Whole Fresh', 'magnis', 603.66, 1);