insert into brand (name)
values ('Cooler Master'),
       ('Intel'),
       ('AMD'),
       ('Seasonic'),
       ('be quiet!'),
       ('Noctua'),
       ('ThermalTake'),
       ('Asus'),
       ('MSI'),
       ('Fractal Design'),
       ('G.Skill'),
       ('Samsung'),
       ('Kingston'),
       ('WD'),
       ('Seagate'),
       ('NZXT');