version: "3.9"
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - "/c/Users/sasha/IdeaProjects/geek-eshop-02-15/db-data:/var/lib/postgresql/data"
    networks:
      default:

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      default:

networks:
  default:
    external:
      name: geek-eshop