version: "3.9"
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ./../../db-data:/var/lib/postgresql/data
    networks:
      default:

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - "6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      default:

  cloud-config-app:
    container_name: spring-cloud-config
    image: shuricans/spring-cloud-config:lesson_9
    restart: unless-stopped
    ports:
      - "8888"
    networks:
      default:

  eureka-app:
    container_name: spring-eureka
    image: shuricans/spring-eureka:lesson_9
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      default:

  cloud-gateway:
    container_name: spring-cloud-gateway
    image: shuricans/spring-cloud-gateway:lesson_9
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      EUREKA_HOST: spring-eureka
      EUREKA_PORT: 8761
    networks:
      default:

  picture-service-app:
    container_name: shop-picture-service-api-app
    image: shuricans/shop-picture-service-api-app:lesson_9
    restart: unless-stopped
    ports:
      - "8080"
    environment:
      EUREKA_HOST: spring-eureka
      EUREKA_PORT: 8761
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
      GATEWAY_HOST: spring-cloud-gateway
      GATEWAY_PORT: 8080
    volumes:
      - ./../../storage:/storage
    networks:
      default:

  backend-app:
    container_name: shop-backend-api-app
    image: shuricans/shop-backend-api-app:lesson_9
    restart: unless-stopped
    ports:
      - "8080"
    environment:
      EUREKA_HOST: spring-eureka
      EUREKA_PORT: 8761
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
      GATEWAY_HOST: spring-cloud-gateway
      GATEWAY_PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      default:

  admin-app:
    container_name: shop-admin-app
    image: shuricans/shop-admin-app:lesson_9
    restart: unless-stopped
    ports:
      - "8080"
    environment:
      EUREKA_HOST: spring-eureka
      EUREKA_PORT: 8761
      CONFIG_HOST: spring-cloud-config
      CONFIG_PORT: 8888
      DB_HOST: db
      DB_PORT: 5432
      GATEWAY_HOST: spring-cloud-gateway
      GATEWAY_PORT: 8080
    volumes:
      - ./../../storage:/storage
    networks:
      default:

networks:
  default:
    external:
      name: geek-eshop