version: "3.9"
services:
  cloud-config-app:
    container_name: spring-cloud-config
    image: spring-cloud-config:lesson_8
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      spring.cloud.config.server.native.search-locations: /config-repo
    volumes:
      - ~/geek-eshop/lesson_8/config-repo-prod:/config-repo
    networks:
      default:

  eureka-app:
    container_name: spring-eureka
    image: spring-eureka:lesson_8
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      default:

  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - ~/db-data:/var/lib/postgresql/data
    networks:
      default:

networks:
  default:
    external:
      name: db